name: CI - release

on: workflow_dispatch

jobs:
  release:
    name: Job - release

    env:
      OUTPUT_DIR: out
    runs-on: ubuntu-latest

    steps:
      - name: Init Go SDK
        uses: actions/setup-go@v2
        with:
          go-version: '1.17'

      - name: Show Go Env
        run: go env && echo -e "\n" && go tool dist list

      - name: Checkout Code
        uses: actions/checkout@v2

      - name: Show Workspace
        run: tree . -L 1

      - name: Build WebDAV
        run: bash webdav.sh -a -o ${{ env.OUTPUT_DIR }}

      - name: Show Output
        run: tree ${{ env.OUTPUT_DIR }} -L 1

      - uses: actions/upload-artifact@v2
        with:
          name: build-artifact
          path: ${{ env.OUTPUT_DIR }}
